export default {
    frontend: [
        {
            type: 'html',
            title: 'HTML',
            number: '7',
            html: '<p>Text om HTML</p>',
            id: 1,
        },
        {
            type: 'css',
            title: 'CSS',
            number: '8',
            html: '',
            id: 2,
        },
        {
            type: 'sass',
            title: 'SASS',
            number: '8',
            html: '<p>Text om SASS och BEM</p>',
            id: 3,
        },
        {
            type: 'javascript',
            title: 'Javascript',
            number: '8',
            html: '<p>Text om Javascript</p>',
            id: 4,
        },
        {
            type: 'react',
            title: 'React',
            number: '8',
            html:
                '<p>React är det ramverk jag jobbat mest i hittills. Jag har gjort ett flertal react-projekt på fritiden. Bland annat frontenden i <a href="">Hamster-Wars</a>, som var ett skolarbete jag gjorde våren 2020.</p>',
            id: 5,
        },
        {
            type: 'nextjs',
            title: 'Next.js',
            number: '7',
            html: '<p>Text om Nextjs</p>',
            id: 6,
        },
        {
            type: 'typescript',
            title: 'Typescript',
            number: '5',
            html: '<p>Text om Typescript</p>',
            id: 7,
        },
        {
            type: 'reactSpring',
            title: 'React-Spring',
            number: '5',
            html: '<p>Text om React-Spring</p>',
            id: 8,
        },
        {
            type: 'redux',
            title: 'Redux',
            number: '6',
            html: '<p>Text om Redux</p>',
            id: 9,
        },
        {
            type: 'github',
            title: 'GitHub',
            number: '7',
            html: '<p>Text om GitHub</p>',
            id: 10,
        },
    ],
    backend: [
        {
            type: 'wordpress',
            title: 'Wordpress',
            number: '7',
            html: '<p>Text om Wordpress</p>',
            id: 11,
        },
        {
            type: 'php',
            title: 'Php',
            number: '6',
            html: '<p>Text om PHP</p>',
            id: 12,
        },
        {
            type: 'nodejs',
            title: 'Node.js',
            number: '7',
            html: '<p>Text om Node</p>',
            id: 13,
        },
        {
            type: 'mysql',
            title: 'MySql',
            number: '5',
            html: '<p>Text om SASS och BEM</p>',
            id: 14,
        },
        {
            type: 'python',
            title: 'Python',
            number: '4',
            html: '<p>Text om Python</p>',
            id: 15,
        },
        {
            type: 'django',
            title: 'Django',
            number: '5',
            html: '<p>Text om Django</p>',
            id: 16,
        },
        {
            type: 'wagtail',
            title: 'Wagtail',
            number: '6',
            html: '<p>Text om Wagtail</p>',
            id: 17,
        },
    ],
};
